name: Build AppImage SLAM Server

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      GCP_CREDENTIALS:
        required: true
      REPO_READ_TOKEN:
        required: true
      ARTIFACT_READ_ONLY_GCP_CREDENTIALS:
        required: true
  push:
    branches: main
    paths-ignore:
      - 'README.md'

env:
  GOPRIVATE: "github.com/viamrobotics/*,go.viam.com/*"
  GOOGLE_APPLICATION_CREDENTIALS_FILENAME: "google-credentials.json"

jobs:
  appimage_orbslam:
    name: AppImage Build
    strategy:
      matrix:
        include:
          - arch: [x64, qemu-host]
            image: ghcr.io/viamrobotics/canon:amd64-cache
            platform: linux/amd64
          - arch: [arm64, qemu-host]
            image: ghcr.io/viamrobotics/canon:arm64-cache
            platform: linux/arm64
    runs-on: ${{ matrix.arch }}
    container:
      image: ${{ matrix.image }}
      options: --platform ${{ matrix.platform }}
    timeout-minutes: 180
    outputs:
      date: ${{ steps.build_test_app.outputs.date }}

    steps:
    - name: Configure git for private repos
      run: |
        sudo -u testbot bash -lc 'echo "machine github.com login viambot password ${{ secrets.REPO_READ_TOKEN }}" > ~/.netrc'

    - name: Check out code in slam directory
      uses: actions/checkout@v3
      with:
        submodules: recursive
        path: slam
   
    - name: Clean
      run: |
        chown -R testbot .
        sudo -u testbot bash -lc 'cd slam/slam-libraries && make clean-all'
    
    - name: make bufinstall buf
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 5
        max_attempts: 3
        retry_on: timeout
        shell: bash
        command: |
          chown -R testbot .
          sudo -u testbot bash -lc 'cd slam/slam-libraries && make bufinstall buf'

    - name: make setuporb
      run: |
        sudo -u testbot bash -lc 'cd slam/slam-libraries && make setuporb'

    - name: make buildorb
      run: |
        sudo -u testbot bash -lc 'cd slam/slam-libraries && make buildorb'

    - name: make testorb
      run: |
        sudo -u testbot bash -lc 'cd slam/slam-libraries && make testorb'

    - name: Copy orb_grpc_server binary
      if: matrix.platform == 'linux/amd64'
      run: |
        sudo cp slam/slam-libraries/viam-orb-slam3/bin/orb_grpc_server /usr/local/bin/orb_grpc_server

    - name: Check out code in rdk directory
      if: matrix.platform == 'linux/amd64'
      uses: actions/checkout@v3
      with:
        repository: viamrobotics/rdk
        path: rdk

    - name: Create GCP Credential File from secret
      if: matrix.platform == 'linux/amd64'
      run: |
        GOOGLE_APPLICATION_CREDENTIALS=`pwd`/${GOOGLE_APPLICATION_CREDENTIALS_FILENAME}
        echo "${{ secrets.ARTIFACT_READ_ONLY_GCP_CREDENTIALS }}" >> ${GOOGLE_APPLICATION_CREDENTIALS}
        echo "GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}" >> $GITHUB_ENV

    - name: Run rdk slam integration tests
      if: matrix.platform == 'linux/amd64'
      run: |
        sudo --preserve-env=GOOGLE_APPLICATION_CREDENTIALS -u testbot bash -lc 'cd rdk/services/slam/builtin && sudo go test -v -run TestOrbslamIntegration'

    - name: Build appimage
      run: sudo -u testbot bash -lc 'cd slam/slam-libraries && make BUILD_CHANNEL="latest" appimageorb'

    - name: Authorize GCP Upload
      uses: google-github-actions/auth@v0.4.3
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    
    - name: Deploy Files
      uses: google-github-actions/upload-cloud-storage@v0.5.0
      with:
        headers: "Cache-Control: no-cache"
        path: 'slam/slam-libraries/packaging/appimages/deploy/'
        destination: 'packages.viam.com/apps/slam-servers/'
        glob: '*'
        parent: false
        gzip: false
  appimage_cartographer:
    name: AppImage Build
    strategy:
      matrix:
        include:
          - arch: [x64, qemu-host]
            image: ghcr.io/viamrobotics/canon:amd64-cache
            platform: linux/amd64
          - arch: [arm64, qemu-host]
            image: ghcr.io/viamrobotics/canon:arm64-cache
            platform: linux/arm64
    runs-on: ${{ matrix.arch }}
    container:
      image: ${{ matrix.image }}
      options: --platform ${{ matrix.platform }}
    timeout-minutes: 180
    outputs:
      date: ${{ steps.build_test_app.outputs.date }}

    steps:
    - name: Configure git for private repos
      run: |
        sudo -u testbot bash -lc 'echo "machine github.com login viambot password ${{ secrets.REPO_READ_TOKEN }}" > ~/.netrc'

    - name: Check out code in slam directory
      uses: actions/checkout@v3
      with:
        submodules: recursive
        path: slam
   
    - name: Clean
      run: |
        chown -R testbot .
        sudo -u testbot bash -lc 'cd slam/slam-libraries && make clean-all'
    
    - name: make bufinstall buf
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 5
        max_attempts: 3
        retry_on: timeout
        shell: bash
        command: |
          chown -R testbot .
          sudo -u testbot bash -lc 'cd slam/slam-libraries && make bufinstall buf'

    - name: make setupcarto
      run: |
        sudo -u testbot bash -lc 'cd slam/slam-libraries && make setupcarto'

    - name: make buildcarto
      run: |
        sudo -u testbot bash -lc 'cd slam/slam-libraries && make buildcarto'

    - name: make testcarto
      run: |
        sudo -u testbot bash -lc 'cd slam/slam-libraries && make testcarto'

    - name: Copy carto_grpc_server binary
      if: matrix.platform == 'linux/amd64'
      run: |
        sudo cp slam/slam-libraries/viam-cartographer/build/carto_grpc_server /usr/local/bin/carto_grpc_server

    - name: Check out code in rdk directory
      if: matrix.platform == 'linux/amd64'
      uses: actions/checkout@v3
      with:
        repository: viamrobotics/rdk
        path: rdk

    - name: Create GCP Credential File from secret
      if: matrix.platform == 'linux/amd64'
      run: |
        GOOGLE_APPLICATION_CREDENTIALS=`pwd`/${GOOGLE_APPLICATION_CREDENTIALS_FILENAME}
        echo "${{ secrets.ARTIFACT_READ_ONLY_GCP_CREDENTIALS }}" >> ${GOOGLE_APPLICATION_CREDENTIALS}
        echo "GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}" >> $GITHUB_ENV

    - name: Run rdk slam integration tests
      if: matrix.platform == 'linux/amd64'
      run: |
        sudo --preserve-env=GOOGLE_APPLICATION_CREDENTIALS -u testbot bash -lc 'cd rdk/services/slam/builtin && sudo go test -v -run TestCartographerIntegration'

    - name: Build appimage
      run: sudo -u testbot bash -lc 'cd slam/slam-libraries && make BUILD_CHANNEL="latest" appimagecarto'

    - name: Authorize GCP Upload
      uses: google-github-actions/auth@v0.4.3
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    
    - name: Deploy Files
      uses: google-github-actions/upload-cloud-storage@v0.5.0
      with:
        headers: "Cache-Control: no-cache"
        path: 'slam/slam-libraries/packaging/appimages/deploy/'
        destination: 'packages.viam.com/apps/slam-servers/'
        glob: '*'
        parent: false
        gzip: false
