name: Main Branch Update

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]
    paths-ignore:
      - 'README.md'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

# To test workflow updates you need to work in a branch directly on viamrobotics/slam
# and tag your working branch instead of @main in any viamrobotics/slam "uses" below.
# Don't forget to tag back to @main before merge.

jobs:
  gotest:
    uses: viamrobotics/slam/.github/workflows/gotest.yml@main
