name: Pull Request Update

concurrency: 
  group: pullrequest-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    branches: [ 'main' ]
    types: [ 'opened', 'reopened', 'synchronize' ]

# To test workflow updates you need to work in a branch directly on viamrobotics/slam
# and tag your working branch instead of @main in any viamrobotics/slam "uses" below.
# Don't forget to tag back to @main before merge.

jobs:
  test:
    uses: viamrobotics/slam/.github/workflows/test.yml@DATA-134-appimage-workflow

  # This lets people add an "appimage" tag to have appimages built for the PR
  appimage:
    needs: test
    if: contains(github.event.pull_request.labels.*.name, 'appimage')
    uses: viamrobotics/slam/.github/workflows/appimage.yml@DATA-134-appimage-workflow
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
