name: Test

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      REPO_READ_TOKEN:
        required: true
      BUF_TOKEN:
        required: true
      ARTIFACT_READ_ONLY_GCP_CREDENTIALS:
        required: true

env:
  GOPRIVATE: "github.com/viamrobotics/*,go.viam.com/*"
  GOOGLE_APPLICATION_CREDENTIALS_FILENAME: "google-credentials.json"

jobs:
  build_and_test:
    name: Build and Test
    strategy:
      matrix:
        include:
          - arch: [x64, qemu-host]
            image: ghcr.io/viamrobotics/canon:amd64-cache
            platform: linux/amd64
          - arch: [arm64, qemu-host]
            image: ghcr.io/viamrobotics/canon:arm64-cache
            platform: linux/arm64
    runs-on: ${{ matrix.arch }}
    container:
      image: ${{ matrix.image }}
      options: --platform ${{ matrix.platform }}
    timeout-minutes: 180

    steps:
    - name: Configure git for private repos
      run: |
        sudo -u testbot bash -lc 'echo "machine github.com login viambot password ${{ secrets.REPO_READ_TOKEN }}" > ~/.netrc'

    - name: Check out code in slam directory
      uses: actions/checkout@v3
      with:
        submodules: recursive
        path: slam

    - name: Verify no uncommitted changes from make format
      run: |
        cd slam
        git init
        git add .
        chown -R testbot .
        sudo -u testbot bash -lc 'cd slam-libraries && make format-setup format'
        GEN_DIFF=$(git status -s)

        if [ -n "$GEN_DIFF" ]; then
            echo '"make format" resulted in changes not in git' 1>&2
            git status
            exit 1
        fi

    - name: Test
      run: |
        sudo -u testbot bash -lc 'cd slam/slam-libraries && export BUF_TOKEN=${{ secrets.BUF_TOKEN }} && make orbslam-all'

    - name: Copy orb_grpc_server binary
      if: matrix.platform == 'linux/amd64'
      run: |
        sudo cp slam/slam-libraries/viam-orb-slam3/bin/orb_grpc_server /usr/local/bin/orb_grpc_server

    - name: Check out code in rdk directory
      if: matrix.platform == 'linux/amd64'
      uses: actions/checkout@v3
      with:
        repository: viamrobotics/rdk
        path: rdk

    - name: Create GCP Credential File from secret
      if: matrix.platform == 'linux/amd64'
      run: |
        GOOGLE_APPLICATION_CREDENTIALS=`pwd`/${GOOGLE_APPLICATION_CREDENTIALS_FILENAME}
        echo "${{ secrets.ARTIFACT_READ_ONLY_GCP_CREDENTIALS }}" >> ${GOOGLE_APPLICATION_CREDENTIALS}
        echo "GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}" >> $GITHUB_ENV

    - name: Run rdk slam integration tests
      if: matrix.platform == 'linux/amd64'
      run: |
        sudo --preserve-env=GOOGLE_APPLICATION_CREDENTIALS -u testbot bash -lc 'cd rdk/services/slam/builtin && go test -v -run TestOrbslamIntegration'
