name: Test

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      ARTIFACT_READ_ONLY_GCP_CREDENTIALS:
        required: true

env:
  GOPRIVATE: "github.com/viamrobotics/*,go.viam.com/*"
  GOOGLE_APPLICATION_CREDENTIALS_FILENAME: "google-credentials.json"

jobs:
  format:
    name: Format
    runs-on: [x64, qemu-host]
    container:
      image: ghcr.io/viamrobotics/canon:amd64-cache
      options: --platform linux/amd64
    timeout-minutes: 30
    steps:
    - name: Check out code in slam directory
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Verify no uncommitted changes from make format
      run: |
        git init
        git add .
        chown -R testbot .
        sudo -u testbot bash -lc 'cd slam-libraries && make format-setup format'
        GEN_DIFF=$(git status -s)

        if [ -n "$GEN_DIFF" ]; then
            echo '"make format" resulted in changes not in git' 1>&2
            git status
            exit 1
        fi

  check_modified_files:
    name: Check modified files
    outputs:
      run_carto: ${{ steps.check_files.outputs.run_carto }}
      run_orb: ${{ steps.check_files.outputs.run_orb }}
    runs-on: [x64, qemu-host]
    container:
      image: ghcr.io/viamrobotics/canon:amd64-cache
      options: --platform linux/amd64
    timeout-minutes: 30
    steps:
    - name: Check out code in slam directory
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Check modified files
      id: check_files
      run: |
        echo "Listing modified files..."
        git diff --name-only HEAD^ HEAD
        echo "Check paths of modified files..."
        git diff --name-only HEAD^ HEAD &gt; files.txt
        echo "::set-output name=run_carto::false"
        echo "::set-output name=run_orb::false"
        while IFS= read -r file
        do
          echo $file
          if [[ $file != slam-libraries/viam-orb-slam3/* ]]; then
            echo "This modified file is not under 'viam-orb-slam3'"
            echo "::set-output name=run_carto::true"
          fi
          if [[ $file != slam-libraries/viam-cartographer/* ]]; then
            echo "This modified file is not under 'viam-cartographer'"
            echo "::set-output name=run_orb::true"
          fi

  build_and_test_orb:
    name: Build and Test Orbslam
    needs: check_modified_files
    if: needs.check_modified_files.outputs.run_orb == 'true'
    strategy:
      matrix:
        include:
          - arch: [x64, qemu-host]
            image: ghcr.io/viamrobotics/canon:amd64-cache
            platform: linux/amd64
          - arch: [arm64, qemu-host]
            image: ghcr.io/viamrobotics/canon:arm64-cache
            platform: linux/arm64
    runs-on: ${{ matrix.arch }}
    container:
      image: ${{ matrix.image }}
      options: --platform ${{ matrix.platform }}
    timeout-minutes: 180

    steps:
    - name: Check out code in slam directory
      uses: actions/checkout@v3
      with:
        submodules: recursive
        path: slam

    - name: make buf
      timeout-minutes: 5
      run: |
        sudo -u testbot bash -lc 'cd slam/slam-libraries && make buf'

    - name: make setuporb
      run: |
        sudo -u testbot bash -lc 'cd slam/slam-libraries && make setuporb'

    - name: make buildorb
      run: |
        sudo -u testbot bash -lc 'cd slam/slam-libraries && make buildorb'

    - name: make testorb
      run: |
        sudo -u testbot bash -lc 'cd slam/slam-libraries && make testorb'

    - name: Copy orb_grpc_server binary
      if: matrix.platform == 'linux/amd64'
      run: |
        sudo cp slam/slam-libraries/viam-orb-slam3/bin/orb_grpc_server /usr/local/bin/orb_grpc_server

    - name: Check out code in rdk directory
      if: matrix.platform == 'linux/amd64'
      uses: actions/checkout@v3
      with:
        repository: viamrobotics/rdk
        path: rdk

    - name: Create GCP Credential File from secret
      if: matrix.platform == 'linux/amd64'
      run: |
        GOOGLE_APPLICATION_CREDENTIALS=`pwd`/${GOOGLE_APPLICATION_CREDENTIALS_FILENAME}
        echo "${{ secrets.ARTIFACT_READ_ONLY_GCP_CREDENTIALS }}" >> ${GOOGLE_APPLICATION_CREDENTIALS}
        echo "GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}" >> $GITHUB_ENV

    - name: Run rdk slam integration tests
      if: matrix.platform == 'linux/amd64'
      run: |
        sudo --preserve-env=GOOGLE_APPLICATION_CREDENTIALS -u testbot bash -lc 'cd rdk/services/slam/builtin && sudo go test -v -run TestOrbslamIntegration'

  build_and_test_cartographer:
    name: Build and Test Cartographer
    needs: check_modified_files
    if: needs.check_modified_files.outputs.run_carto == 'true'
    strategy:
      matrix:
        include:
          - arch: [x64, qemu-host]
            image: ghcr.io/viamrobotics/canon:amd64-cache
            platform: linux/amd64
          - arch: [arm64, qemu-host]
            image: ghcr.io/viamrobotics/canon:arm64-cache
            platform: linux/arm64
    runs-on: ${{ matrix.arch }}
    container:
      image: ${{ matrix.image }}
      options: --platform ${{ matrix.platform }}
    timeout-minutes: 180

    steps:
    - name: Check out code in slam directory
      uses: actions/checkout@v3
      with:
        submodules: recursive
        path: slam

    - name: make setupcarto
      run: |
        sudo -u testbot bash -lc 'cd slam/slam-libraries && make setupcarto'

    - name: make buildcarto
      run: |
        sudo -u testbot bash -lc 'cd slam/slam-libraries && make buildcarto'
